### ISSUE TITLE
Adopter registration shows incorrect data to the user

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#858] opened 2024-07-30 20:14 UTC
As a user, when you fill out the adopter registration for the first time, Opencast may show you incorrect information about what is being sent to register.opencast.org. Specifically, if “send usage statistics” was not selected before and you select it, Opencast would show that no statistics information are sent.

https://github.com/user-attachments/assets/d2515534-c857-4bb7-b8aa-bd70da0d0bbd

**Comment by dennis531** [comment] 2024-08-01 13:12
The linked opencast pull request should fix this. The problem is that the api doesn't provide the statistics information to the admin ui if statistics are not allowed.

**Comment by Arnei** [comment] 2024-09-26 09:34
Linked PR is merged, so I'll close this. Just reopen if this is not fixed.

**Closed by Arnei** 2024-09-26 09:34 UTC
