### ISSUE TITLE
Using tab key in the create/modify event/series pop-up is not working as expected

### ISSUE THREAD

**Issue by snoesberger** [opencast/opencast-admin-interface#543] opened 2024-06-04 09:47 UTC
When I create or modify an event or series, the tab key does not work as expected. I'd expect the cursor to move from one input field to the next when I press the tab key, but instead the cursor jumps to the "Next" button and then outside the pop-up to the main window.

**Comment by Arnei** [comment] 2024-06-04 09:59
Duplicate of https://github.com/opencast/opencast-admin-interface/issues/233.
Related https://github.com/opencast/opencast-admin-interface/pull/480

**Closed** 2024-06-04 10:00 UTC
