### ISSUE TITLE
Warning: Rendering components directly into document.body is discouraged

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#547] opened 2024-06-04 09:56 UTC
When you open the UI, you get a warning which we might want to take a look at:

> Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app. react-dom.development.js:67:29

**Comment by ziegenberg** [comment] 2024-06-04 10:08
Duplicate of #408

**Closed by ziegenberg** 2024-06-04 10:08 UTC
