### ISSUE TITLE
Event page updates break modal state

### ISSUE THREAD

**Issue by gregorydlogan** [opencast/opencast-admin-interface#852] opened 2024-07-24 16:14 UTC
When modifying the event ACL (and probably metadata, this is untested) for an event in the events list, the *displayed* event switches to the **same LINE in the events list**, partially, when the events page updates.  Symptoms:

- The title of the modal changes
- The displayed ACL does **not**, and the data is persisted in either event depending on how the issue was triggered
  - I suspect this would be true of *any* pane in the modal, so this is potential data corruption issue wrt to metadata, and/or ACLs
- Switching tabs in the modal displays the correct data for the event, but it might not be the event you think you're on since it's changed underneath you!

Here's the major issue: If you're working alone you hopefully/probably won't see this much since the event order likely only changes when you're working.  In a multi-admin situation, that's not true and it could quite conceivably trigger all kinds of fun data corruption issues.

**Comment by lkiesow** [comment] 2024-07-24 21:11
This Video shows how to reproduce the problem:

https://github.com/user-attachments/assets/1be15bab-57a2-4160-8455-4dd53074e4a8

**Comment by dennis531** [comment] 2024-07-25 08:08
I cannot reproduce this problem on the main branch. However, the bug is available on develop.opencast. Does this server have the current development state of this repository?

I think this bug was fixed by the modal navigation refactoring in #817. However, I found a bug where some action buttons in the table always open the metadata page. I create a pull request for this bug.

**Comment by lkiesow** [comment] 2024-07-27 10:28
Can confirm that this is fixed in `main`. Just not in the last release. Will be included in the next release though.

**Closed by lkiesow** 2024-07-27 10:28 UTC
Labels: type:bug
