### ISSUE TITLE
Password change for my user is not possible 

### ISSUE THREAD

**Issue by Melanie-Koller** [opencast/opencast-admin-interface#454] opened 2024-05-24 05:29 UTC
I can’t change the password for my own user.

![10](https://github.com/opencast/opencast-admin-interface/assets/57887263/5f9493c4-5585-4a5c-8162-b8f399fa357d)

**Comment by Arnei** [comment] 2024-06-04 13:54
Could not reproduce the issue. What I tried:
- Login as admin
- Create a new user
- Give it all the admin UI roles
- Login as new user
- Change password for new user in admin ui
- Logout and log back in as new user with new password.
- It works.

Could you provide more information, such as user roles and if the user is provided by remote system? (ILIAS, Shibboleth, etc.).

**Comment by Melanie-Koller** [comment] 2024-06-04 14:15
Maybe it's more a problem with my user. 

![Bildschirmfoto 2024-06-04 um 16 12 18](https://github.com/opencast/opencast-admin-interface/assets/57887263/b767c9de-ebd9-4b8b-993a-04618f5f6d6a)


![Bildschirmfoto 2024-06-04 um 16 12 34](https://github.com/opencast/opencast-admin-interface/assets/57887263/e7bc3415-8cf2-4ccf-80aa-1bed387df716)

I don't have more information about that.

**Comment by kruemelm0nsta** [comment] 2024-06-05 07:19
#356 same issue

**Comment by lkiesow** [comment] 2024-06-08 10:22
Closing this as a duplicate of https://github.com/opencast/opencast-admin-interface/issues/356

**Closed** 2024-06-08 10:22 UTC
Labels: type:bug
