### ISSUE TITLE
Presenter filter display in event table broken 

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#794] opened 2024-07-02 20:44 UTC
The filter has no value. It should!

![Screenshot from 2024-07-02 22-07-17](https://github.com/opencast/opencast-admin-interface/assets/1008395/a7b508ac-45a9-41b4-a63c-776a4cb3e457)

**Comment by Arnei** [comment] 2024-07-03 06:45
Duplicate of #538

**Closed by Arnei** 2024-07-03 06:45 UTC
Labels: type:bug
