### ISSUE TITLE
necessity of green hooks on Presenter and Contributor in Event Details

### ISSUE THREAD

**Issue by kruemelm0nsta** [opencast/opencast-admin-interface#629] opened 2024-06-05 11:24 UTC
leftover or have they a function?
![grafik](https://github.com/opencast/opencast-admin-interface/assets/131258682/868f0f3a-b3e4-4862-9f3d-4fb34371328c)

**Comment by ziegenberg** [comment] 2024-06-05 19:01
Hi @kruemelm0nsta, I can't reproduce this error on https://develop.opencast.org at the moment. Can you describe in more detail when this is happening?

**Comment by geichelberger** [comment] 2024-06-05 19:14
I can reproduce it here:
https://admin-interface.opencast.org/admin-ui/index.html#/events/series

**Comment by ziegenberg** [comment] 2024-06-05 19:40
So we broke something between the last release in may and now.

**Comment by ziegenberg** [comment] 2024-06-05 20:03
According to @kruemelm0nsta we should assign this issue to @KatrinIhler. It was originally implemented for "someone"...

**Comment by ferishili** [comment] 2024-06-05 20:05
Just take a look at the linked PR, I don't think that is so complicated!

**Closed** 2024-06-10 10:17 UTC
Labels: question, bugbash
