### ISSUE TITLE
No i18n for EVENTS.EVENTS.NEW.SOURCE.UPLOAD.SUBTITLES.SHORT

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [opencast/opencast-admin-interface#380] opened 2024-05-08 07:07 UTC
The i18n Entry for `EVENTS.EVENTS.NEW.SOURCE.UPLOAD.SUBTITLES.SHORT` is missing:

<img width="773" alt="image" src="https://github.com/opencast/opencast-admin-interface/assets/53210931/5f97d663-87d5-40c8-8e54-c58c7b0034b8">

**Comment by ziegenberg** [comment] 2024-05-09 02:22
This is a duplicate of #260

**Closed** 2024-05-17 09:55 UTC
