### ISSUE TITLE
Scheduling tab in event details may show confusing values

### ISSUE THREAD

**Issue by lkiesow** [opencast/opencast-admin-interface#672] opened 2024-06-06 18:01 UTC
If any particular scheduling value is 0 (hour, minute) the value is not shown and you get a cut-off version of the label instead:

For example, this event is scheduled at 1am with a duration of 30 minutes:
![Screenshot from 2024-06-06 19-56-50](https://github.com/opencast/opencast-admin-interface/assets/1008395/0ca819d5-95bc-4bb1-9c61-0031f60961f5)

**Comment by Arnei** [comment] 2024-06-07 06:51
Duplicate of #611

**Closed by Arnei** 2024-06-07 06:51 UTC
Labels: type:bug, bugbash
