### ISSUE TITLE
Tab index not working/existing?

### ISSUE THREAD

**Issue by KatrinIhler** [opencast/opencast-admin-interface#233] opened 2023-12-14 16:32 UTC
In the old Admin UI, you can use Tab to navigate through quite a number of UI elements, for example the fields in the metadata tab. At least that doesn't seem to be working anymore.

**Comment by Arnei** [comment] 2023-12-15 13:28
Related/duplicate of #65

**Closed** 2024-05-24 20:48 UTC
Labels: bug
